#!/usr/bin/env zsh

# global settings
yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         autofocus
yabai -m config window_placement            second_child
yabai -m config window_topmost              on
yabai -m config window_opacity              on
yabai -m config window_opacity_duration     0.0
yabai -m config window_shadow               on
yabai -m config window_border               off
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50
yabai -m config auto_balance                on
yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# general space settings
yabai -m config top_padding                 26
yabai -m config layout                      bsp
yabai -m config top_padding                 10
yabai -m config bottom_padding              10
yabai -m config left_padding                10
yabai -m config right_padding               10
yabai -m config window_gap                  10

# spaces
# create extra spaces
pending_spaces=$(echo 7 - $(yabai -m query --spaces | jq '.[] | .id' | wc -l) | bc)
for i in `seq $pending_spaces`; do
    yabai -m space --create;
done
yabai -m space 1                            --label trash
yabai -m space 2                            --label work
yabai -m space 3                            --label mail
yabai -m space 4                            --label chat
yabai -m space 5                            --label music
yabai -m space 6                            --label photos
yabai -m space 7                            --label monitoring

# disable tiling for floating applications
yabai -m rule --add                         label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add                         label="Firefox" app="^Firefox$" title="(Opening)" manage=off
yabai -m rule --add                         label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add                         label="App Store" app="^App Store$" manage=off
yabai -m rule --add                         label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add                         label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add                         label="Contexts" app="^Contexts$" manage=off
yabai -m rule --add                         label="Disk Utility" app="^Disk Utility$" manage=off
yabai -m rule --add                         label="Zoom" app="^zoom.us$" manage=off
yabai -m rule --add                         label="Calendar" app="^Calendar$" manage=off
yabai -m rule --add                         label="JetBrains Toolbox" app="^JetBrains Toolbox$" manage=off

# pin common apps to dedicated space
yabai -m rule --add                         app="^WhatsApp$" space=chat
yabai -m rule --add                         app="^Messages.*$" space=chat
yabai -m rule --add                         app="^Slack$" space=chat
yabai -m rule --add                         title="^Inbox.*Mail$" space=mail
yabai -m rule --add                         app="^YouTube Music Desktop App$" space=music
yabai -m rule --add                         app="^Photos$" space=photos
yabai -m rule --add                         app="^(WebStorm|RubyMine|PyCharm)$" space=work
yabai -m rule --add                         title="^glances$" space=monitoring
