#!/usr/bin/env sh


# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_placement      exterior
yabai -m config window_border_width          2
yabai -m config window_border_radius         -1
yabai -m config active_window_border_color   0xffb8bb26
yabai -m config normal_window_border_color   0xff7c6f64
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# Status bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "FiraGO:Regular:12.0"
yabai -m config status_bar_icon_font         "FiraCode Nerd Font:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  1   ﬐   
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# Spaces
yabai -m space 1 --label chaos
yabai -m space 2 --label work
yabai -m space 3 --label comms
yabai -m space 4 --label music
yabai -m space 5 --label monitoring

# Disable tiling for floating applications
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Contexts" app="^Contexts$" manage=off

# Pin common apps to dedicated space
yabai -m rule --add app="^WhatsApp$" space=comms
yabai -m rule --add app="^Slack$" space=comms
yabai -m rule --add app="^YouTube Music Desktop App$" space=music
yabai -m rule --add app="^(WebStorm|RubyMine|PyCharm)$" space=work
