#!/bin/bash
PATTERN=$1
DEST=$2
MATCH=$(echo $DEST | cut -d '/' -f 1)
git filter-branch --prune-empty --tree-filter "
if [ ! -e $DEST ]; then 
    mkdir -p $DEST;
    git ls-tree --name-only \$GIT_COMMIT $PATTERN | grep -v ^$MATCH\$ | xargs -I f mv f $DEST;
fi" -f

