format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$env_var\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

[line_break]
disabled = true

