export ZENV=zsh
export ZENV=prezto
export ZSH=$HOME/.oh-my-zsh
export EDITOR=vim
export TERM=xterm-256color
export LC_ALL=en_US.UTF-8
export LANG=en_US.utf8
export GPG_TTY=$(tty)
export AWS_SDK_LOAD_CONFIG=true
unsetopt nomatch
